---
- block:
    - name: Install MongoDB public GPG key
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0C49F3730359A14518585931BC711F9BA15703C6

    - name: Add MongoDB repository into sources.list
      apt_repository: repo="deb http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/3.4 multiverse" state=present

    - name: Install MongoDB Database Server
      apt: pkg=mongodb-org state=present update-cache=yes
